### ISSUE TITLE
bait: the service should provide group metadata that can be used by hosting providers to decorate the landing page

### ISSUE THREAD

**Issue by zalberico** [tloncorp/lure#14]
- Currently the only information passed to the hosting provider is the group information
- From discussion with @lukebuehler it'd be useful if they had other metadata they could use to decorate pages with (group image, group description, etc.)

Assigning this one to @midsum-salrux, but tagging @philipcmonk for context (I know @midsum-salrux and @tomholford will be working on helping with the hosting dashboard flow so the specifics of what metadata is relevant for this should get determined from interacting with Lukas and the hosting team).

**Comment by zalberico** [comment]
Talking to @lukebuehler I have a better idea of this, basically we want to enable the user to be able to customize their invite page that hosting can then render.
- This means there's some more config group side for this.
- Probably for v0 we should just have more generally really good defaults for this that matches hosting's design in figma (maybe using the group image if it exists)

**Comment by zalberico** [comment]
To add some additional context from my conversation with Lukas and Luke this morning:
- James M and Juan are building out the flow seen above (seen entirely in figma) on the hosting side
- They're optimistically targeting next Tuesday, but it may be a couple days longer
- When that flow exists we can then partner with them to wire up the lure pieces to the flow
- The lure pieces include: passing the group and metadata to hosting to render the custom elements on the page, hosting sending the ID info to the lure service once the user makes an account so lure can complete the invitation.

With that in place we'll be able to make sure things look okay by having people at tlon send links to family and friends (we can ask them to create a group for their family or w/e makes sense to make sure this flow is working).

**Comment by zalberico** [comment]
@midsum-salrux and @philipcmonk I see the linked PR, how does hosting query lure to get the info? What's that access look like for them?

**Comment by midsum-salrux** [comment]
You can visit [host]/[inviter]/[token]/metadata.json. An example: https://bait-dev.tlon.io/~possum-midsum-salrux/gatonians/metadata.json

**Comment by zalberico** [comment]
<img width="1121" alt="Screenshot 2023-01-31 at 12 27 26 PM" src="https://user-images.githubusercontent.com/441466/215875175-e4ddbcb8-2521-45a8-a112-6d1a482cd0ba.png">
