### ISSUE TITLE
Use `/lure` for default instead of `/`

### ISSUE THREAD

**Issue by zalberico** [tloncorp/lure#31]
We don't want to bind to the root `/` by default, we should use `/lure`. This was a request from hosting, but having some app base there just makes future changes/extensions easier.

**Comment by midsum-salrux** [comment]
This is already the behavior. https://github.com/tloncorp/lure/blob/develop/desk/app/bait.hoon#L67

**Comment by zalberico** [comment]
Tagging @philipcmonk just in case I'm confused (he asked me to make this because he thought the default was root?)

**Comment by philipcmonk** [comment]
The default lure service should use bait-dev.tlon.io/lure, so we can unbind
root there
