### ISSUE TITLE
Invites to secret groups are very secret

### ISSUE THREAD

**Issue by lukestiles** [tloncorp/lure#37]
An invite to a secret group is possible, which we may not want for now. If we do, we will need to be able to surface a bit more information. 

<img width="1673" alt="Screenshot 2023-02-03 at 5 32 11 PM" src="https://user-images.githubusercontent.com/1903610/216739263-9ebb842d-6907-48c8-9e1c-e3a562b68919.png">

**Comment by lukestiles** [comment]
Also, I am already in the group - Tlon Internal - but an invite is issued. The invite doesn't go away when accepted, and looks quite odd when attempting to accept. 

<img width="1666" alt="Screenshot 2023-02-03 at 5 40 41 PM" src="https://user-images.githubusercontent.com/1903610/216739721-7c9bb118-c0d4-4c9a-9913-e14536bc95c7.png">

**Comment by zalberico** [comment]
A little more about secret group invites here: https://github.com/tloncorp/landscape-apps/issues/1847#issuecomment-1412606560

I think we probably do want the capability? Secret to me implies not searchable, but still can invite people too. I could see the argument go either way.

Thanks for filing - either way the invite should work 😁
