### ISSUE TITLE
Reel: Groups should have a single invite link (using the group host) and a single bait service

### ISSUE THREAD

**Issue by zalberico** [tloncorp/lure#39]
- Right now when the invite link is enabled, the reel service configuration from landscape of the person (admin) who creates it is what determines the link (both the patp and what bait service is used depending on what they have configured in their ship's landscape settings for lure)
- We want the link to always use the group host as the link provider and we want to the bait service to be able to be set in the group admin panel (though it'll just be tlon.network at first).

This does a couple of things:
- There will be one invite link for a group.
- The invite link will work as long as the group host is up (as opposed to having different invite links created by different admins)
- The invite link for a group will use a single bait-service (not whatever bait service a particular admin has configured).

@lukebuehler does the above sound correct?

@philipcmonk this was from a conversation with @lukebuehler and @midsum-salrux this morning in gathertown. Hosting needs another week or so before they will be ready, @midsum-salrux is helping homestead team this week.

**Comment by midsum-salrux** [comment]
> The invite link for a group will use a single bait-service (not whatever bait service a particular admin has configured).

I think it should use the bait service configured on the group host's ship.

**Comment by zalberico** [comment]
@lukebuehler does that work or did you say want it configurable per group even if both groups are hosted by the same host ship? I think using the bait service configured on the group host's ship makes sense.
