### ISSUE TITLE
loups: "errored" on tile

### ISSUE THREAD

**Issue by zalberico** [tloncorp/lure#40]
<img width="266" alt="Screenshot 2023-02-06 at 12 07 47 PM" src="https://user-images.githubusercontent.com/441466/217037589-44eb3918-e87e-4184-82bc-3f8d1ccb3e7d.png">

After a groups upgrade I'm now seeing this.

The vat info says it's running:
```
%lure
  /sys/kelvin:      [%zuse 417] [%zuse 416] [%zuse 415]
  base hash:        0v2.3t3a8.rn2cv.60fr4.oljmc.ufr3e.fvt9l.l70b7.kv0oe.q9uro.capsf
  %cz hash:         0v2.3t3a8.rn2cv.60fr4.oljmc.ufr3e.fvt9l.l70b7.kv0oe.q9uro.capsf
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          remote
  source ship:      ~samnec-dozzod-marzod
  source desk:      %lure
  source aeon:      19
  kids desk:        ~
  pending updates:  ~
  ```
  
  I don't see any other useful info in dojo output.

**Comment by patosullivan** [comment]
I'm seeing the same thing. It was working as of yesterday.

![image](https://user-images.githubusercontent.com/1221094/217055140-464cd1e7-dea1-4b3f-85b1-bf0e9ca8310e.png)

**Comment by ashelkovnykov** [comment]
`~samnec-dozzod-marzod` was the testing ground for PR #36, which broke the glob many times before fixing it.
